#!/bin/bash

# Variables
SERVER_USER="your_username"
SERVER_IP="your_server_ip"
SERVER_DIR="dir"
GIT_REPO="your_git_repository_url"
BRANCH="branch"

# SSH into the server and execute commands
ssh $SERVER_USER@SERVER_IP << EOF

cd $SERVER_DIR

git pull origin $BRANCH

npm install

npm run build

npm run start

pm2 restart all

EOF

echo "Deployment complete."
